SUCCESS = 'SUCCESS'
TIME_OUT = 'TIME_OUT' 
INVALID_INPUT_DATA = 'INVALID_INPUT_DATA'

TABLE_NOT_FOUND = 'TABLE_NOT_FOUND'
TABLE_ALREADY_EXISTS = 'TABLE_ALREADY_EXISTS'

USER_NOT_FOUND = 'USER_NOT_FOUND'