SUCCESS = 'SUCCESS'
TIME_OUT = 'TIME_OUT'
ERROR = 'ERROR' 
INVALID_INPUT_DATA = 'INVALID_INPUT_DATA'

TABLE_NOT_FOUND = 'TABLE_NOT_FOUND'
TABLE_ALREADY_EXISTS = 'TABLE_ALREADY_EXISTS'
ITEM_ALREADY_EXISTS = 'ITEM_ALREADY_EXISTS'

ITEM_NOT_FOUND = 'ITEM_NOT_FOUND'